server:
  port: 8090
  servlet:
    session:
      timeout: 10m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yusufbek200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  access:
    key: tHaX54Hwk^YMzKd@e@p7#70@!@*6d7676K8C1%T&hBnrzgqK28o
    expiration-time: 720000


app:
  admin:
    username: admin@admin.com
    password: admin

#    folder:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: sirojiddinit@gmail.com
#    password: cqcgezivhvqlor
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  servlet:
#    multipart:
#      max-request-size: 100MB
#      max-file-size: 100MB
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#logging:
#  file:
#    name: codingbat.log